/**
 * Elevated and session-only actions — **generated from policy metadata**.
 *
 * rbac.md § "Elevated and audited actions" carries the single list of actions that require a
 * fresh authentication, and says plainly that the table "is generated by `pnpm test:permissions`
 * from the `elevated: true` entries in the `policy.ts` files. Edit the registry, not this
 * table." This module is that generator, and the same functions produce the violations that
 * make a forgotten elevation a build failure rather than a shipped hole.
 */

import type { Capability } from "./capabilities";
import { isCapabilityPolicy, type RouteKey } from "./policy";
import type { PolicyRegistry, RegistryEntry } from "./registry";

/**
 * Capabilities that mint or widen authority. A route requiring one of these must carry
 * `elevated: true`, or an explicit `elevated: false` with a written reason.
 *
 * Derived from the elevated-action table in rbac.md — every action on it is reachable only
 * through one of these — and enumerated here because rbac.md names the set without listing it.
 * Each entry says which row of that table put it here:
 *
 * - `instance:admin` — granting instance admin, impersonation, purge, key rotation, exports,
 *   organisation deletion, `sees_all`-adjacent instance surfaces.
 * - `instance:manage_plugins` — creating or changing an `auth.*` plugin, which is an
 *   authentication surface.
 * - `workspace:manage_members` — granting `sees_all` on a membership is a reach change and is
 *   never self-grantable.
 * - `workspace:manage_roles` — a role editor can mint authority up to the editor's own rank.
 * - `project:manage_members` — the two reach-affecting fields, `parent_id` and `owner_team_id`.
 * - `api_key:manage` — a workspace service key is a standing credential bounded by its
 *   creator's authority.
 * - `webhook:manage` — a standing outbound data channel carrying every event in the owner's
 *   reach to an arbitrary endpoint, indefinitely (`WH-14`).
 * - `change:manage` — the change-freeze override.
 */
export const AUTHORITY_GRANTING: readonly Capability[] = [
  "instance:admin",
  "instance:manage_plugins",
  "workspace:manage_members",
  "workspace:manage_roles",
  "project:manage_members",
  "api_key:manage",
  "webhook:manage",
  "change:manage",
];

const AUTHORITY_GRANTING_SET: ReadonlySet<string> = new Set(AUTHORITY_GRANTING);

/** Every route under the instance surface is authority-adjacent by construction. */
export function isInstanceRoute(routeKey: RouteKey): boolean {
  const path = routeKey.slice(routeKey.indexOf(" ") + 1);
  return path === "/api/instance" || path.startsWith("/api/instance/");
}

export type ElevatedAction = {
  readonly routeKey: RouteKey;
  readonly capability?: Capability;
  readonly sessionOnly: boolean;
  readonly source: string;
};

/** The elevated-action list, generated. This is what rbac.md's table is rendered from. */
export function elevatedActions(registry: PolicyRegistry): ElevatedAction[] {
  return registry.entries
    .filter((entry) => entry.policy.elevated === true)
    .map((entry) => ({
      routeKey: entry.routeKey,
      capability: isCapabilityPolicy(entry.policy)
        ? entry.policy.capability
        : undefined,
      sessionOnly: entry.policy.sessionOnly === true,
      source: entry.source,
    }));
}

/**
 * The session-only routes, generated.
 *
 * `tests/permissions/session-only.test.ts` enumerates its cases from this — from the
 * `sessionOnly` field in the registry, never from a second hand-kept list.
 */
export function sessionOnlyRoutes(registry: PolicyRegistry): RouteKey[] {
  return registry.entries
    .filter((entry) => entry.policy.sessionOnly === true)
    .map((entry) => entry.routeKey);
}

export type ElevationViolation = {
  readonly routeKey: RouteKey;
  readonly reason: string;
};

/**
 * Routes the elevation rule catches that declare neither `elevated: true` nor a reasoned
 * `elevated: false`.
 *
 * "A new authority-minting route that nobody remembered to list therefore fails the build
 * instead of shipping unprotected."
 */
export function elevationViolations(
  registry: PolicyRegistry,
): ElevationViolation[] {
  const violations: ElevationViolation[] = [];

  for (const entry of registry.entries) {
    if (!elevationRuleApplies(entry)) continue;
    if (entry.policy.elevated === true) continue;
    if (
      entry.policy.elevated === false &&
      (entry.policy.elevationExemptionReason ?? "").trim() !== ""
    ) {
      continue;
    }
    violations.push({
      routeKey: entry.routeKey,
      reason: whyElevationApplies(entry),
    });
  }

  return violations;
}

function elevationRuleApplies(entry: RegistryEntry): boolean {
  if (isInstanceRoute(entry.routeKey)) return true;
  return (
    isCapabilityPolicy(entry.policy) &&
    AUTHORITY_GRANTING_SET.has(entry.policy.capability)
  );
}

function whyElevationApplies(entry: RegistryEntry): string {
  if (isInstanceRoute(entry.routeKey)) {
    return "an /api/instance/* route must declare elevated: true, or elevated: false with a written reason";
  }
  const capability = isCapabilityPolicy(entry.policy)
    ? entry.policy.capability
    : "unknown";
  return `${capability} is in AUTHORITY_GRANTING — declare elevated: true, or elevated: false with a written reason`;
}

/**
 * Every elevated route must also be session-only.
 *
 * "Elevated actions … are accepted only from a browser session: an API key, an `is_mcp` key or
 * an impersonation session is refused `403 session_required`." An elevated route that forgets
 * `sessionOnly` is reachable from a personal API key, which is the whole hole.
 */
export function elevatedWithoutSessionOnly(
  registry: PolicyRegistry,
): RouteKey[] {
  return registry.entries
    .filter(
      (entry) =>
        entry.policy.elevated === true && entry.policy.sessionOnly !== true,
    )
    .map((entry) => entry.routeKey);
}

/** Render the generated table exactly as rbac.md carries it, so the doc can be diffed against it. */
export function renderElevatedActionsMarkdown(
  registry: PolicyRegistry,
): string {
  const actions = elevatedActions(registry);
  const lines = [
    "| Route | Capability | Session-only |",
    "| --- | --- | --- |",
  ];
  for (const action of actions) {
    lines.push(
      `| \`${action.routeKey}\` | ${action.capability ? `\`${action.capability}\`` : "—"} | ${action.sessionOnly ? "yes" : "**no**"} |`,
    );
  }
  return lines.join("\n");
}
