/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/portal/__root'
import { Route as IndexRouteImport } from './routes/portal/index'
import { Route as ApprovalsRouteImport } from './routes/portal/approvals'
import { Route as CatalogueRouteImport } from './routes/portal/catalogue'
import { Route as SignInRouteImport } from './routes/portal/sign-in'
import { Route as SubmissionsRefRouteImport } from './routes/portal/submissions/$ref'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRefRoute = SubmissionsRefRouteImport.update({
  id: '/submissions/$ref',
  path: '/submissions/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/catalogue': typeof CatalogueRoute
  '/sign-in': typeof SignInRoute
  '/submissions/$ref': typeof SubmissionsRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/catalogue': typeof CatalogueRoute
  '/sign-in': typeof SignInRoute
  '/submissions/$ref': typeof SubmissionsRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/catalogue': typeof CatalogueRoute
  '/sign-in': typeof SignInRoute
  '/submissions/$ref': typeof SubmissionsRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/approvals' | '/catalogue' | '/sign-in' | '/submissions/$ref'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/approvals' | '/catalogue' | '/sign-in' | '/submissions/$ref'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/catalogue'
    | '/sign-in'
    | '/submissions/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CatalogueRoute: typeof CatalogueRoute
  SignInRoute: typeof SignInRoute
  SubmissionsRefRoute: typeof SubmissionsRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$ref': {
      id: '/submissions/$ref'
      path: '/submissions/$ref'
      fullPath: '/submissions/$ref'
      preLoaderRoute: typeof SubmissionsRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  CatalogueRoute: CatalogueRoute,
  SignInRoute: SignInRoute,
  SubmissionsRefRoute: SubmissionsRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
