import assert from "node:assert/strict";
import test from "node:test";
import { canonicalRoute, inventoryRouteSet } from "./check-inventory.mjs";
import {
  extractFullPaths,
  renderRouteMetadata,
} from "./lib/route-metadata.mjs";

test("G5 canonicalizes query variants and dynamic parameter names", () => {
  assert.equal(
    canonicalRoute("/agent/projects/$projectKey/work?layout=list"),
    "/agent/projects/{}/work",
  );
  assert.equal(
    canonicalRoute("/agent/projects/{key}/work?layout=board"),
    "/agent/projects/{}/work",
  );
  assert.deepEqual(
    inventoryRouteSet(
      [
        "| Name | Route | Kind | Stage | Status |",
        "| Work list | `/agent/projects/{key}/work?layout=list` | route | P1 | 🟡 |",
        "| Work board | `/agent/projects/{key}/work?layout=board` | route | P1 | ⬜ |",
        "| Toolbar | — | overlay | P1 | ⬜ |",
      ].join("\n"),
      { activeOnly: true },
    ),
    new Set(["/agent/projects/{}/work"]),
  );
});

test("G5 extracts both ordinary and portal root paths from TanStack's generated type metadata", () => {
  const tree = `export interface FileRouteTypes {\n  fullPaths:\n    | '/'\n    | '/agent/projects/$projectKey/work'\n  fileRoutesByTo: X\n}`;
  assert.deepEqual(extractFullPaths(tree, "tree.ts"), [
    "/",
    "/agent/projects/$projectKey/work",
  ]);
  assert.equal(
    renderRouteMetadata({
      agent: ["/agent/projects/$projectKey/work"],
      portal: ["/"],
    }),
    [
      "// Generated by scripts/ci/generate-route-metadata.mjs from TanStack Router trees.",
      "// Do not edit by hand; check:inventory verifies this file against both trees.",
      "export const generatedRouteMetadata = {",
      '  agent: ["/agent/projects/$projectKey/work"],',
      '  portal: ["/"],',
      "} as const;",
      "",
    ].join("\n"),
  );
});

test("G5 leaves not-started inventory URLs planned while enforcing active screens", () => {
  const source = [
    "| Screen | Route | Kind | Stage | Status |",
    "| Current | `/portal` | route | P0 | 🟡 |",
    "| Future | `/portal/requests` | route | P3 | ⬜ |",
  ].join("\n");
  assert.deepEqual(
    inventoryRouteSet(source, { activeOnly: true }),
    new Set(["/portal"]),
  );
  assert.deepEqual(
    inventoryRouteSet(source),
    new Set(["/portal", "/portal/requests"]),
  );
});
