/**
 * Drizzle table definitions for issue #8 Slice 2's shadow-mode evidence store.
 *
 * Declared HERE, not in `apps/api/src/database/schema.ts` — that file, and the `schema`
 * object `apps/api/src/database/index.ts` builds from it, are #308's lane. Drizzle does not
 * require a table to be registered in a central `schema` object to be queried: `pgTable(...)`
 * returns an ordinary typed table reference, usable with the shared `db` export
 * (`apps/api/src/database/index.ts`'s default export) exactly like any table declared there.
 * `pnpm check:vocabulary` scans every workspace file for `pgTable("name", …)`, not only
 * `schema.ts`, so both names still have to be — and are — registered in
 * `docs/01-architecture/data-model.md`.
 *
 * The migration that creates these two tables is
 * `apps/api/drizzle/0069_policy_shadow_tables.sql`, hand-written (following
 * `docs/04-engineering/migrations.md`'s "hand-written SQL" allowance and migration 0067's
 * own precedent) rather than generated by `drizzle-kit generate` against `schema.ts` — that
 * command only ever diffs `schema.ts`, which this table pair deliberately does not touch.
 * `apps/api/drizzle/meta/0069_snapshot.json` carries forward main's 0068 snapshot (including
 * its `is_system` change) with a fresh `id` and `prevId` pointing at that 0068 snapshot, so
 * the chain stays valid for whoever next runs `drizzle-kit generate` — it will see no
 * `schema.ts` change at this step, correctly, and emit nothing about these tables.
 *
 * See `docs/01-architecture/data-model.md`'s "Policy shadow evidence (issue #8, Slice 2)"
 * section for the authoritative column list and the outcome vocabulary, and
 * `shadow-store.ts` for how these are read and written.
 */

import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  date,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";

/** The five outcomes a shadow comparison can resolve to — the addendum's own vocabulary. */
export const SHADOW_OUTCOMES = [
  "agree",
  "legacy_allow_policy_deny",
  "legacy_deny_policy_allow",
  "unevaluated",
  "evaluator_error",
] as const;

export type ShadowOutcome = (typeof SHADOW_OUTCOMES)[number];

/** The four outcomes worth a `policy_shadow_event` row — every outcome except `agree`. */
export const SHADOW_EVENT_OUTCOMES = SHADOW_OUTCOMES.filter(
  (outcome): outcome is Exclude<ShadowOutcome, "agree"> => outcome !== "agree",
);

/**
 * One row per `(day, route_key, outcome, reason_code)` bucket, incremented on every request
 * the shadow middleware evaluates — agreements included. This is what answers the
 * addendum's coverage requirement ("every request … is counted … A router with unevaluated
 * requests is not clean") without needing a row per request.
 */
export const policyShadowTallyTable = pgTable(
  "policy_shadow_tally",
  {
    id: text("id").primaryKey(),
    day: date("day", { mode: "string" }).notNull(),
    routeKey: text("route_key").notNull(),
    routerGroup: text("router_group").notNull(),
    outcome: text("outcome").notNull().$type<ShadowOutcome>(),
    reasonCode: text("reason_code"),
    count: bigint("count", { mode: "number" }).notNull().default(1),
    lastSeenAt: timestamp("last_seen_at", { mode: "date", withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index("policy_shadow_tally_route_key_day_idx").on(
      table.routeKey,
      table.day,
    ),
    check(
      "policy_shadow_tally_outcome_check",
      sql`${table.outcome} IN ('agree', 'legacy_allow_policy_deny', 'legacy_deny_policy_allow', 'unevaluated', 'evaluator_error')`,
    ),
    check("policy_shadow_tally_count_positive", sql`${table.count} > 0`),
    // `.nullsNotDistinct()` — the SQL migration declares `UNIQUE NULLS NOT DISTINCT`
    // (0069_policy_shadow_tables.sql); without this the Drizzle-side declaration would
    // describe an ordinary UNIQUE (NULLs distinct), disagreeing with the real constraint
    // the database actually enforces. Ordinary review of PR #323.
    unique("policy_shadow_tally_bucket_unique")
      .on(table.day, table.routeKey, table.outcome, table.reasonCode)
      .nullsNotDistinct(),
  ],
);

/**
 * One row per non-`agree` shadow disagreement, capped at 50 per `(day, route_key, outcome,
 * reason_code)` bucket by `shadow-store.ts`'s writer (an `INSERT … SELECT … WHERE` guard,
 * not a database constraint — see that file for why an occasional over-cap row under a race
 * is an accepted, documented residual rather than a correctness requirement).
 *
 * **Never** carries a request body, a header, a secret, an email or a name — ids only, plus
 * the decision's own log-only `code`/`diagnostic` fields (already documented as client-safe
 * to log, never client-safe to return, by `evaluator.ts`'s own `PolicyDecision` comments).
 */
export const policyShadowEventTable = pgTable(
  "policy_shadow_event",
  {
    id: text("id").primaryKey(),
    day: date("day", { mode: "string" }).notNull(),
    routeKey: text("route_key").notNull(),
    routerGroup: text("router_group").notNull(),
    policyKind: text("policy_kind"),
    policyCapability: text("policy_capability"),
    outcome: text("outcome").notNull().$type<Exclude<ShadowOutcome, "agree">>(),
    reasonCode: text("reason_code"),
    legacyAllowed: boolean("legacy_allowed"),
    legacyStatus: integer("legacy_status"),
    policyAllowed: boolean("policy_allowed"),
    policyStatus: integer("policy_status"),
    policyCode: text("policy_code"),
    diagnostic: text("diagnostic"),
    identityKind: text("identity_kind"),
    workspaceId: text("workspace_id"),
    traceId: text("trace_id"),
    createdAt: timestamp("created_at", { mode: "date", withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index("policy_shadow_event_route_key_created_at_idx").on(
      table.routeKey,
      table.createdAt.desc(),
    ),
    index("policy_shadow_event_bucket_idx").on(
      table.day,
      table.routeKey,
      table.outcome,
      table.reasonCode,
    ),
    check(
      "policy_shadow_event_outcome_check",
      sql`${table.outcome} IN ('legacy_allow_policy_deny', 'legacy_deny_policy_allow', 'unevaluated', 'evaluator_error')`,
    ),
  ],
);
